name: Build
permissions:
  contents: read

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution (Release x64)
        run: msbuild AnimalArkShelter.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AnimalArkShelter-Release-x64
          path: |
            AnimalArkShelter/bin/x64/Release/AnimalArkShelter.dll
            AnimalArkShelter/AnimalArkShelter.ini
